name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: DOCKERHUB
    steps:
    - uses: actions/checkout@v3
    - name: build-image-Pyhon
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
          image: wissemgh5/bsimg_mssql17
          registry: docker.io
          dockerfile: ./MSSQL17/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          push: true
          tags: ${{ github.sha }}
    - name: scan docker images
      uses: azure/container-scan@v0
      with:
         image-name: wissemgh5/bsimg_mssql17:${{ github.sha }}
         severity-threshold: HIGH
         run-quality-checks: true
